### ISSUE TITLE
перелистование фотографий

### ISSUE THREAD

**Issue by tsvetkovpro** [lkazberova/react-photo-feed#2]
добрый день, а можно сделать чтобы по щелчку левой кнопкой мыши, на открытой фотографии показывалась следущая фотография?

**Comment by lkazberova** [comment]
Да, можно это реализовать. Как будет время - сделаю.

**Comment by tsvetkovpro** [comment]
уважаемая, получается ты просто скопировала этот репозиторий и его не ты написала?

**Comment by lkazberova** [comment]
На чем основывается данное мнение? Мне даже любопытно)
